import type { PluginTemplate } from '@/types/plugin';

export const pluginTemplates: PluginTemplate[] = [
  // ---------------------------------------------------------------------------
  // 1. Vintage Passive EQ (Pultec EQP-1A style)
  // ---------------------------------------------------------------------------
  {
    id: 'vintage-passive-eq',
    name: 'Vintage Passive EQ',
    type: 'eq',
    description:
      'A warm, musical passive equalizer inspired by classic tube-driven designs from the 1950s. Features separate boost and attenuation controls for low and high frequencies with a broad, gentle curve that adds harmonic richness. Ideal for sweetening vocals, adding weight to drums, and shaping the tonal character of any source.',
    icon: 'AudioWaveform',
    tags: ['eq', 'vintage', 'passive', 'analog', 'tube', 'mastering'],
    inspirations: ['Pultec EQP-1A', 'Pultec MEQ-5', 'Tube-Tech PE 1C'],
    parameters: [
      {
        id: 'low-boost',
        name: 'lowBoost',
        label: 'Low Boost',
        type: 'float',
        min: 0,
        max: 10,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
      {
        id: 'low-atten',
        name: 'lowAtten',
        label: 'Low Atten',
        type: 'float',
        min: 0,
        max: 10,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
      {
        id: 'low-freq',
        name: 'lowFreq',
        label: 'Low Frequency',
        type: 'choice',
        defaultValue: 1,
        choices: ['20', '30', '60', '100'],
        unit: 'Hz',
      },
      {
        id: 'high-boost',
        name: 'highBoost',
        label: 'High Boost',
        type: 'float',
        min: 0,
        max: 10,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
      {
        id: 'high-atten',
        name: 'highAtten',
        label: 'High Atten',
        type: 'float',
        min: 0,
        max: 10,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
      {
        id: 'high-freq',
        name: 'highFreq',
        label: 'High Frequency',
        type: 'choice',
        defaultValue: 2,
        choices: ['3000', '4000', '5000', '8000', '10000', '12000', '16000'],
        unit: 'Hz',
      },
      {
        id: 'bandwidth',
        name: 'bandwidth',
        label: 'Bandwidth',
        type: 'float',
        min: 0,
        max: 10,
        defaultValue: 5,
        step: 0.1,
      },
      {
        id: 'output',
        name: 'output',
        label: 'Output',
        type: 'float',
        min: -12,
        max: 12,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 2. Parametric EQ (FabFilter Pro-Q style)
  // ---------------------------------------------------------------------------
  {
    id: 'parametric-eq',
    name: 'Parametric EQ',
    type: 'eq',
    description:
      'A precise, fully parametric equalizer with four independent bands, each offering full control over frequency, gain, Q factor, and filter type. Built for surgical corrections and creative tonal shaping with transparent, phase-accurate processing. Suitable for mixing, mastering, and sound design applications.',
    icon: 'SlidersHorizontal',
    tags: ['eq', 'parametric', 'surgical', 'mixing', 'mastering', 'transparent'],
    inspirations: ['FabFilter Pro-Q 3', 'Waves Q10', 'DMG Audio EQuilibrium'],
    parameters: [
      // Band 1
      {
        id: 'band1-freq',
        name: 'band1Freq',
        label: 'Band 1 Freq',
        type: 'float',
        min: 20,
        max: 20000,
        defaultValue: 80,
        step: 1,
        unit: 'Hz',
      },
      {
        id: 'band1-gain',
        name: 'band1Gain',
        label: 'Band 1 Gain',
        type: 'float',
        min: -30,
        max: 30,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
      {
        id: 'band1-q',
        name: 'band1Q',
        label: 'Band 1 Q',
        type: 'float',
        min: 0.1,
        max: 30,
        defaultValue: 1.0,
        step: 0.01,
      },
      {
        id: 'band1-type',
        name: 'band1Type',
        label: 'Band 1 Type',
        type: 'choice',
        defaultValue: 4,
        choices: ['Bell', 'Low Shelf', 'High Shelf', 'Low Cut', 'High Cut', 'Notch'],
      },
      // Band 2
      {
        id: 'band2-freq',
        name: 'band2Freq',
        label: 'Band 2 Freq',
        type: 'float',
        min: 20,
        max: 20000,
        defaultValue: 500,
        step: 1,
        unit: 'Hz',
      },
      {
        id: 'band2-gain',
        name: 'band2Gain',
        label: 'Band 2 Gain',
        type: 'float',
        min: -30,
        max: 30,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
      {
        id: 'band2-q',
        name: 'band2Q',
        label: 'Band 2 Q',
        type: 'float',
        min: 0.1,
        max: 30,
        defaultValue: 1.0,
        step: 0.01,
      },
      {
        id: 'band2-type',
        name: 'band2Type',
        label: 'Band 2 Type',
        type: 'choice',
        defaultValue: 0,
        choices: ['Bell', 'Low Shelf', 'High Shelf', 'Low Cut', 'High Cut', 'Notch'],
      },
      // Band 3
      {
        id: 'band3-freq',
        name: 'band3Freq',
        label: 'Band 3 Freq',
        type: 'float',
        min: 20,
        max: 20000,
        defaultValue: 2500,
        step: 1,
        unit: 'Hz',
      },
      {
        id: 'band3-gain',
        name: 'band3Gain',
        label: 'Band 3 Gain',
        type: 'float',
        min: -30,
        max: 30,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
      {
        id: 'band3-q',
        name: 'band3Q',
        label: 'Band 3 Q',
        type: 'float',
        min: 0.1,
        max: 30,
        defaultValue: 1.0,
        step: 0.01,
      },
      {
        id: 'band3-type',
        name: 'band3Type',
        label: 'Band 3 Type',
        type: 'choice',
        defaultValue: 0,
        choices: ['Bell', 'Low Shelf', 'High Shelf', 'Low Cut', 'High Cut', 'Notch'],
      },
      // Band 4
      {
        id: 'band4-freq',
        name: 'band4Freq',
        label: 'Band 4 Freq',
        type: 'float',
        min: 20,
        max: 20000,
        defaultValue: 8000,
        step: 1,
        unit: 'Hz',
      },
      {
        id: 'band4-gain',
        name: 'band4Gain',
        label: 'Band 4 Gain',
        type: 'float',
        min: -30,
        max: 30,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
      {
        id: 'band4-q',
        name: 'band4Q',
        label: 'Band 4 Q',
        type: 'float',
        min: 0.1,
        max: 30,
        defaultValue: 1.0,
        step: 0.01,
      },
      {
        id: 'band4-type',
        name: 'band4Type',
        label: 'Band 4 Type',
        type: 'choice',
        defaultValue: 0,
        choices: ['Bell', 'Low Shelf', 'High Shelf', 'Low Cut', 'High Cut', 'Notch'],
      },
      // Global
      {
        id: 'output-gain',
        name: 'outputGain',
        label: 'Output Gain',
        type: 'float',
        min: -24,
        max: 24,
        defaultValue: 0,
        step: 0.1,
        unit: 'dB',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 3. VCA Compressor (SSL G-Bus style)
  // ---------------------------------------------------------------------------
  {
    id: 'vca-compressor',
    name: 'VCA Compressor',
    type: 'compressor',
    description:
      'A punchy, fast-acting VCA compressor modeled after the legendary bus compressors found in large-format mixing consoles. Known for its ability to glue mixes together with musical transient control and a solid low end. Stepped attack and release controls provide repeatable settings across sessions.',
    icon: 'Gauge',
    tags: ['compressor', 'vca', 'bus', 'glue', 'mixing', 'analog'],
    inspirations: ['SSL G-Bus Compressor', 'API 2500', 'Neve 33609'],
    parameters: [
      {
        id: 'threshold',
        name: 'threshold',
        label: 'Threshold',
        type: 'float',
        min: -40,
        max: 0,
        defaultValue: -10,
        step: 0.5,
        unit: 'dB',
      },
      {
        id: 'ratio',
        name: 'ratio',
        label: 'Ratio',
        type: 'choice',
        defaultValue: 1,
        choices: ['2:1', '4:1', '8:1', '10:1', '20:1'],
      },
      {
        id: 'attack',
        name: 'attack',
        label: 'Attack',
        type: 'choice',
        defaultValue: 1,
        choices: ['0.1', '0.3', '1', '3', '10', '30'],
        unit: 'ms',
      },
      {
        id: 'release',
        name: 'release',
        label: 'Release',
        type: 'choice',
        defaultValue: 2,
        choices: ['100', '300', '600', '1200', 'Auto'],
        unit: 'ms',
      },
      {
        id: 'makeup',
        name: 'makeup',
        label: 'Makeup Gain',
        type: 'float',
        min: 0,
        max: 20,
        defaultValue: 0,
        step: 0.5,
        unit: 'dB',
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 100,
        step: 1,
        unit: '%',
      },
      {
        id: 'sidechain-filter',
        name: 'sidechainFilter',
        label: 'Sidechain HPF',
        type: 'bool',
        defaultValue: 0,
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 4. Optical Compressor (LA-2A style)
  // ---------------------------------------------------------------------------
  {
    id: 'optical-compressor',
    name: 'Optical Compressor',
    type: 'compressor',
    description:
      'A smooth, program-dependent optical compressor that uses an electro-luminescent element and photoresistor to achieve naturally musical gain reduction. Its simple two-knob interface belies the complex, frequency-dependent compression beneath. Perfect for vocals, bass, and any source that benefits from transparent dynamic control.',
    icon: 'Sun',
    tags: ['compressor', 'optical', 'vintage', 'vocal', 'smooth', 'tube'],
    inspirations: ['Teletronix LA-2A', 'Tube-Tech CL 1B', 'Universal Audio LA-3A'],
    parameters: [
      {
        id: 'peak-reduction',
        name: 'peakReduction',
        label: 'Peak Reduction',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 40,
        step: 1,
      },
      {
        id: 'gain',
        name: 'gain',
        label: 'Gain',
        type: 'float',
        min: 0,
        max: 40,
        defaultValue: 20,
        step: 0.5,
        unit: 'dB',
      },
      {
        id: 'mode',
        name: 'mode',
        label: 'Mode',
        type: 'choice',
        defaultValue: 0,
        choices: ['Compress', 'Limit'],
      },
      {
        id: 'emphasis',
        name: 'emphasis',
        label: 'HF Emphasis',
        type: 'float',
        min: 0,
        max: 10,
        defaultValue: 0,
        step: 0.1,
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 100,
        step: 1,
        unit: '%',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 5. Plate Reverb (EMT 140 style)
  // ---------------------------------------------------------------------------
  {
    id: 'plate-reverb',
    name: 'Plate Reverb',
    type: 'reverb',
    description:
      'A lush plate reverb emulating the dense, smooth reflections of a large suspended metal sheet vibrated by a transducer. Produces a bright, evenly diffused reverb tail that sits beautifully behind vocals and snare drums without cluttering the mix. The damping control tames high-frequency decay for a darker, more intimate character.',
    icon: 'Waves',
    tags: ['reverb', 'plate', 'vintage', 'vocal', 'dense', 'studio'],
    inspirations: ['EMT 140', 'Soundtoys Little Plate', 'UAD Plate 140'],
    parameters: [
      {
        id: 'decay',
        name: 'decay',
        label: 'Decay',
        type: 'float',
        min: 0.5,
        max: 8.0,
        defaultValue: 2.5,
        step: 0.1,
        unit: 's',
      },
      {
        id: 'damping',
        name: 'damping',
        label: 'Damping',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
      {
        id: 'pre-delay',
        name: 'preDelay',
        label: 'Pre-Delay',
        type: 'float',
        min: 0,
        max: 200,
        defaultValue: 20,
        step: 1,
        unit: 'ms',
      },
      {
        id: 'low-cut',
        name: 'lowCut',
        label: 'Low Cut',
        type: 'float',
        min: 20,
        max: 500,
        defaultValue: 80,
        step: 1,
        unit: 'Hz',
      },
      {
        id: 'high-cut',
        name: 'highCut',
        label: 'High Cut',
        type: 'float',
        min: 2000,
        max: 20000,
        defaultValue: 12000,
        step: 100,
        unit: 'Hz',
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 30,
        step: 1,
        unit: '%',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 6. Algorithmic Reverb (Valhalla Room style)
  // ---------------------------------------------------------------------------
  {
    id: 'algorithmic-reverb',
    name: 'Algorithmic Reverb',
    type: 'reverb',
    description:
      'A versatile algorithmic reverb engine offering a wide range of room simulations from tight ambiences to vast cathedrals. Features independent control over early reflections, late diffusion, and frequency-dependent decay. Designed for low CPU usage while delivering studio-quality spatial processing across any genre.',
    icon: 'Box',
    tags: ['reverb', 'algorithmic', 'room', 'hall', 'spatial', 'versatile'],
    inspirations: ['Valhalla Room', 'Lexicon 480L', 'FabFilter Pro-R'],
    parameters: [
      {
        id: 'size',
        name: 'size',
        label: 'Room Size',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
      {
        id: 'decay',
        name: 'decay',
        label: 'Decay Time',
        type: 'float',
        min: 0.1,
        max: 30.0,
        defaultValue: 2.0,
        step: 0.1,
        unit: 's',
      },
      {
        id: 'diffusion',
        name: 'diffusion',
        label: 'Diffusion',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 70,
        step: 1,
        unit: '%',
      },
      {
        id: 'damping',
        name: 'damping',
        label: 'Damping',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
      {
        id: 'pre-delay',
        name: 'preDelay',
        label: 'Pre-Delay',
        type: 'float',
        min: 0,
        max: 500,
        defaultValue: 20,
        step: 1,
        unit: 'ms',
      },
      {
        id: 'early-late',
        name: 'earlyLate',
        label: 'Early / Late',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
      {
        id: 'mod-rate',
        name: 'modRate',
        label: 'Mod Rate',
        type: 'float',
        min: 0.01,
        max: 5.0,
        defaultValue: 0.5,
        step: 0.01,
        unit: 'Hz',
      },
      {
        id: 'mod-depth',
        name: 'modDepth',
        label: 'Mod Depth',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 20,
        step: 1,
        unit: '%',
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 25,
        step: 1,
        unit: '%',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 7. Tape Delay (Echoplex style)
  // ---------------------------------------------------------------------------
  {
    id: 'tape-delay',
    name: 'Tape Delay',
    type: 'delay',
    description:
      'A warm, characterful tape delay emulating the sound of vintage tape echo machines with their inherent wow, flutter, and saturation. Each repeat degrades naturally, losing high-frequency content and gaining subtle modulation just like a real tape loop. Produces organic, musical echoes that sit naturally in a mix.',
    icon: 'Disc',
    tags: ['delay', 'tape', 'echo', 'vintage', 'analog', 'modulation'],
    inspirations: ['Maestro Echoplex EP-3', 'Roland RE-201 Space Echo', 'Strymon El Capistan'],
    parameters: [
      {
        id: 'time',
        name: 'time',
        label: 'Delay Time',
        type: 'float',
        min: 50,
        max: 2000,
        defaultValue: 375,
        step: 1,
        unit: 'ms',
      },
      {
        id: 'feedback',
        name: 'feedback',
        label: 'Feedback',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 40,
        step: 1,
        unit: '%',
      },
      {
        id: 'wow',
        name: 'wow',
        label: 'Wow',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 15,
        step: 1,
        unit: '%',
      },
      {
        id: 'flutter',
        name: 'flutter',
        label: 'Flutter',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 20,
        step: 1,
        unit: '%',
      },
      {
        id: 'tone',
        name: 'tone',
        label: 'Tone',
        type: 'float',
        min: 200,
        max: 12000,
        defaultValue: 4000,
        step: 10,
        unit: 'Hz',
      },
      {
        id: 'saturation',
        name: 'saturation',
        label: 'Saturation',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 30,
        step: 1,
        unit: '%',
      },
      {
        id: 'age',
        name: 'age',
        label: 'Tape Age',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 30,
        step: 1,
        unit: '%',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 8. Digital Delay (H-Delay style)
  // ---------------------------------------------------------------------------
  {
    id: 'digital-delay',
    name: 'Digital Delay',
    type: 'delay',
    description:
      'A clean, precise digital delay with tempo sync, ping-pong stereo mode, and built-in filtering. Offers pristine repeats that maintain fidelity across long feedback chains, along with filtering options to shape the echoes from bright and present to dark and distant. Essential for rhythmic delays and production effects.',
    icon: 'Clock',
    tags: ['delay', 'digital', 'sync', 'ping-pong', 'stereo', 'clean'],
    inspirations: ['Waves H-Delay', 'SoundToys EchoBoy', 'Valhalla Delay'],
    parameters: [
      {
        id: 'time',
        name: 'time',
        label: 'Delay Time',
        type: 'float',
        min: 1,
        max: 5000,
        defaultValue: 500,
        step: 1,
        unit: 'ms',
      },
      {
        id: 'sync',
        name: 'sync',
        label: 'Tempo Sync',
        type: 'bool',
        defaultValue: 0,
      },
      {
        id: 'sync-division',
        name: 'syncDivision',
        label: 'Sync Division',
        type: 'choice',
        defaultValue: 3,
        choices: ['1/16', '1/8t', '1/8', '1/4t', '1/4', '1/2', '1/1'],
      },
      {
        id: 'feedback',
        name: 'feedback',
        label: 'Feedback',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 35,
        step: 1,
        unit: '%',
      },
      {
        id: 'ping-pong',
        name: 'pingPong',
        label: 'Ping Pong',
        type: 'bool',
        defaultValue: 0,
      },
      {
        id: 'lp-filter',
        name: 'lpFilter',
        label: 'Low Pass Filter',
        type: 'float',
        min: 200,
        max: 20000,
        defaultValue: 12000,
        step: 10,
        unit: 'Hz',
      },
      {
        id: 'hp-filter',
        name: 'hpFilter',
        label: 'High Pass Filter',
        type: 'float',
        min: 20,
        max: 5000,
        defaultValue: 20,
        step: 1,
        unit: 'Hz',
      },
      {
        id: 'stereo-width',
        name: 'stereoWidth',
        label: 'Stereo Width',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 25,
        step: 1,
        unit: '%',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 9. Subtractive Synth (Minimoog style)
  // ---------------------------------------------------------------------------
  {
    id: 'subtractive-synth',
    name: 'Subtractive Synth',
    type: 'synth',
    description:
      'A classic subtractive synthesizer inspired by the fat, warm analog circuits of legendary monophonic instruments from the 1970s. Features three oscillators with selectable waveforms routed through a resonant ladder filter and shaped by a snappy ADSR envelope. The glide control enables smooth portamento between notes for expressive lead and bass sounds.',
    icon: 'Piano',
    tags: ['synth', 'subtractive', 'analog', 'mono', 'bass', 'lead', 'oscillator'],
    inspirations: ['Minimoog Model D', 'Arturia Mini V', 'Sequential Prophet-5'],
    parameters: [
      {
        id: 'osc1-waveform',
        name: 'osc1Waveform',
        label: 'OSC 1 Wave',
        type: 'choice',
        defaultValue: 0,
        choices: ['Saw', 'Square', 'Triangle', 'Sine', 'Noise'],
      },
      {
        id: 'osc1-octave',
        name: 'osc1Octave',
        label: 'OSC 1 Octave',
        type: 'choice',
        defaultValue: 2,
        choices: ['-2', '-1', '0', '+1', '+2'],
      },
      {
        id: 'osc1-level',
        name: 'osc1Level',
        label: 'OSC 1 Level',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 80,
        step: 1,
        unit: '%',
      },
      {
        id: 'osc2-waveform',
        name: 'osc2Waveform',
        label: 'OSC 2 Wave',
        type: 'choice',
        defaultValue: 0,
        choices: ['Saw', 'Square', 'Triangle', 'Sine', 'Noise'],
      },
      {
        id: 'osc2-detune',
        name: 'osc2Detune',
        label: 'OSC 2 Detune',
        type: 'float',
        min: -100,
        max: 100,
        defaultValue: 7,
        step: 1,
        unit: 'cents',
      },
      {
        id: 'osc2-level',
        name: 'osc2Level',
        label: 'OSC 2 Level',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 60,
        step: 1,
        unit: '%',
      },
      {
        id: 'osc3-waveform',
        name: 'osc3Waveform',
        label: 'OSC 3 Wave',
        type: 'choice',
        defaultValue: 1,
        choices: ['Saw', 'Square', 'Triangle', 'Sine', 'Noise'],
      },
      {
        id: 'osc3-detune',
        name: 'osc3Detune',
        label: 'OSC 3 Detune',
        type: 'float',
        min: -100,
        max: 100,
        defaultValue: -5,
        step: 1,
        unit: 'cents',
      },
      {
        id: 'osc3-level',
        name: 'osc3Level',
        label: 'OSC 3 Level',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 40,
        step: 1,
        unit: '%',
      },
      {
        id: 'filter-cutoff',
        name: 'filterCutoff',
        label: 'Filter Cutoff',
        type: 'float',
        min: 20,
        max: 20000,
        defaultValue: 1200,
        step: 1,
        unit: 'Hz',
      },
      {
        id: 'filter-resonance',
        name: 'filterResonance',
        label: 'Filter Resonance',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 25,
        step: 1,
        unit: '%',
      },
      {
        id: 'filter-env',
        name: 'filterEnv',
        label: 'Filter Env Amount',
        type: 'float',
        min: -100,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
      {
        id: 'amp-attack',
        name: 'ampAttack',
        label: 'Attack',
        type: 'float',
        min: 0.5,
        max: 10000,
        defaultValue: 5,
        step: 0.5,
        unit: 'ms',
      },
      {
        id: 'amp-decay',
        name: 'ampDecay',
        label: 'Decay',
        type: 'float',
        min: 1,
        max: 10000,
        defaultValue: 200,
        step: 1,
        unit: 'ms',
      },
      {
        id: 'amp-sustain',
        name: 'ampSustain',
        label: 'Sustain',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 70,
        step: 1,
        unit: '%',
      },
      {
        id: 'amp-release',
        name: 'ampRelease',
        label: 'Release',
        type: 'float',
        min: 1,
        max: 10000,
        defaultValue: 300,
        step: 1,
        unit: 'ms',
      },
      {
        id: 'glide',
        name: 'glide',
        label: 'Glide',
        type: 'float',
        min: 0,
        max: 1000,
        defaultValue: 0,
        step: 1,
        unit: 'ms',
      },
      {
        id: 'master-volume',
        name: 'masterVolume',
        label: 'Master Volume',
        type: 'float',
        min: -60,
        max: 0,
        defaultValue: -6,
        step: 0.5,
        unit: 'dB',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 10. Tube Saturation (Decapitator style)
  // ---------------------------------------------------------------------------
  {
    id: 'tube-saturation',
    name: 'Tube Saturation',
    type: 'distortion',
    description:
      'A rich, harmonic saturation processor that models the behavior of overdriven vacuum tubes at various stages of breakup. From subtle warmth and presence at low drive settings to aggressive, full-bodied distortion at higher levels, it adds life and dimension to any signal. Multiple saturation styles let you dial in the exact color and character you need.',
    icon: 'Flame',
    tags: ['distortion', 'saturation', 'tube', 'warmth', 'harmonics', 'analog'],
    inspirations: ['Soundtoys Decapitator', 'FabFilter Saturn', 'Softube Harmonics'],
    parameters: [
      {
        id: 'drive',
        name: 'drive',
        label: 'Drive',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 30,
        step: 1,
        unit: '%',
      },
      {
        id: 'style',
        name: 'style',
        label: 'Style',
        type: 'choice',
        defaultValue: 0,
        choices: ['Tube A', 'Tube B', 'Tape', 'Transistor', 'Hard Clip'],
      },
      {
        id: 'tone',
        name: 'tone',
        label: 'Tone',
        type: 'float',
        min: -100,
        max: 100,
        defaultValue: 0,
        step: 1,
      },
      {
        id: 'low-cut',
        name: 'lowCut',
        label: 'Low Cut',
        type: 'float',
        min: 20,
        max: 1000,
        defaultValue: 20,
        step: 1,
        unit: 'Hz',
      },
      {
        id: 'high-cut',
        name: 'highCut',
        label: 'High Cut',
        type: 'float',
        min: 1000,
        max: 20000,
        defaultValue: 20000,
        step: 100,
        unit: 'Hz',
      },
      {
        id: 'output',
        name: 'output',
        label: 'Output',
        type: 'float',
        min: -24,
        max: 0,
        defaultValue: 0,
        step: 0.5,
        unit: 'dB',
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 100,
        step: 1,
        unit: '%',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 11. Analog Chorus (Boss CE-1 style)
  // ---------------------------------------------------------------------------
  {
    id: 'analog-chorus',
    name: 'Analog Chorus',
    type: 'chorus',
    description:
      'A lush, warm chorus effect based on classic bucket-brigade delay line circuits from the late 1970s. Produces rich stereo widening and gentle pitch modulation that thickens guitars, synths, and pads without sounding artificial. Features selectable vibrato and chorus modes for both subtle and dramatic modulation effects.',
    icon: 'Repeat',
    tags: ['chorus', 'analog', 'modulation', 'stereo', 'vintage', 'bbd'],
    inspirations: ['Boss CE-1', 'Roland Juno-60 Chorus', 'TC Electronic Corona'],
    parameters: [
      {
        id: 'rate',
        name: 'rate',
        label: 'Rate',
        type: 'float',
        min: 0.05,
        max: 10.0,
        defaultValue: 0.8,
        step: 0.01,
        unit: 'Hz',
      },
      {
        id: 'depth',
        name: 'depth',
        label: 'Depth',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 60,
        step: 1,
        unit: '%',
      },
      {
        id: 'delay',
        name: 'delay',
        label: 'Delay',
        type: 'float',
        min: 1,
        max: 30,
        defaultValue: 7,
        step: 0.1,
        unit: 'ms',
      },
      {
        id: 'feedback',
        name: 'feedback',
        label: 'Feedback',
        type: 'float',
        min: 0,
        max: 95,
        defaultValue: 10,
        step: 1,
        unit: '%',
      },
      {
        id: 'mode',
        name: 'mode',
        label: 'Mode',
        type: 'choice',
        defaultValue: 0,
        choices: ['Chorus', 'Vibrato'],
      },
      {
        id: 'stereo-width',
        name: 'stereoWidth',
        label: 'Stereo Width',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 80,
        step: 1,
        unit: '%',
      },
      {
        id: 'tone',
        name: 'tone',
        label: 'Tone',
        type: 'float',
        min: 500,
        max: 15000,
        defaultValue: 8000,
        step: 100,
        unit: 'Hz',
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // 12. Vintage Phaser (MXR Phase 90 style)
  // ---------------------------------------------------------------------------
  {
    id: 'vintage-phaser',
    name: 'Vintage Phaser',
    type: 'phaser',
    description:
      'A swooshy, organic phaser effect modeled after the all-pass filter networks found in iconic 1970s stomp boxes. Creates moving notches in the frequency spectrum that produce everything from subtle jet-like sweeps to deep, swirling textures. Selectable 4, 8, or 12 stage operation offers control over the depth and complexity of the phase cancellation pattern.',
    icon: 'Orbit',
    tags: ['phaser', 'modulation', 'vintage', 'guitar', 'sweep', 'analog'],
    inspirations: ['MXR Phase 90', 'Electro-Harmonix Small Stone', 'Boss PH-3'],
    parameters: [
      {
        id: 'rate',
        name: 'rate',
        label: 'Rate',
        type: 'float',
        min: 0.01,
        max: 10.0,
        defaultValue: 0.5,
        step: 0.01,
        unit: 'Hz',
      },
      {
        id: 'depth',
        name: 'depth',
        label: 'Depth',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 70,
        step: 1,
        unit: '%',
      },
      {
        id: 'feedback',
        name: 'feedback',
        label: 'Feedback',
        type: 'float',
        min: 0,
        max: 95,
        defaultValue: 30,
        step: 1,
        unit: '%',
      },
      {
        id: 'stages',
        name: 'stages',
        label: 'Stages',
        type: 'choice',
        defaultValue: 0,
        choices: ['4', '8', '12'],
      },
      {
        id: 'center-freq',
        name: 'centerFreq',
        label: 'Center Frequency',
        type: 'float',
        min: 100,
        max: 5000,
        defaultValue: 1000,
        step: 10,
        unit: 'Hz',
      },
      {
        id: 'stereo',
        name: 'stereo',
        label: 'Stereo',
        type: 'bool',
        defaultValue: 0,
      },
      {
        id: 'mix',
        name: 'mix',
        label: 'Mix',
        type: 'float',
        min: 0,
        max: 100,
        defaultValue: 50,
        step: 1,
        unit: '%',
      },
    ],
  },
];

/**
 * Look up a single plugin template by its unique ID.
 */
export function getTemplateById(id: string): PluginTemplate | undefined {
  return pluginTemplates.find((t) => t.id === id);
}
